# Generated by Django 3.0.7 on 2021-02-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0002_auto_20210206_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_serviceprovider',
            field=models.BooleanField(default=False),
        ),
    ]
