# Generated by Django 3.0.7 on 2021-02-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0003_auto_20210206_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecompletion',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
