# Generated by Django 3.0.7 on 2021-02-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_Section', '0001_initial'),
        ('ServiceProvider', '0004_auto_20210206_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bed_numbers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='coverpicture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profilecompletion',
            name='bed_numbers',
            field=models.CharField(default=20, max_length=120),
        ),
        migrations.AddField(
            model_name='profilecompletion',
            name='coverpicture',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AddField(
            model_name='profilecompletion',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_Section.Department'),
        ),
        migrations.AddField(
            model_name='profilecompletion',
            name='photo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
